version: 4.2.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\nlog
configuration: Release
platform: Any CPU
skip_tags: true
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
  - msbuild /t:restore c:\projects\nlog\NLog.Etw.sln /verbosity:minimal
build:
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal
after_build:
  - msbuild /t:pack c:\projects\nlog\NLog.Etw.sln /p:Version=4.2.0.0 /p:fileversion=%APPVEYOR_BUILD_VERSION% /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=..\artifacts /verbosity:minimal
artifacts:
  - path: 'artifacts\*.nupkg'
  - path: 'artifacts\*.snupkg'
deploy:
- provider: NuGet
  api_key:
    secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
  artifact: /.*\.nupkg/
  on:
    branch: master
test_script:
  - msbuild /t:build c:\projects\nlog\NLog.Etw.sln /p:Version=%APPVEYOR_BUILD_VERSION% /p:Configuration=Debug /p:IncludeSymbols=true /verbosity:minimal
  - nuget.exe install OpenCover -ExcludeVersion -DependencyVersion Ignore
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"c:\projects\nlog\NLog.Etw.Tests\bin\Debug\net452\NLog.Etw.Tests.dll\" -appveyor -noshadow"  -returntargetcode -filter:"+[NLog.Etw]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
