version: 5.0.0.{build}
image: Visual Studio 2022
clone_folder: c:\projects\nlog
configuration: Release
platform: Any CPU
skip_tags: true
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:	
  - ps: .\build.ps1
test_script:
  - msbuild /t:build c:\projects\nlog\NLog.Etw.sln /p:Version=%APPVEYOR_BUILD_VERSION% /p:Configuration=Debug /p:IncludeSymbols=true /verbosity:minimal
  - nuget.exe install OpenCover -ExcludeVersion -DependencyVersion Ignore
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"c:\projects\nlog\NLog.Etw.Tests\bin\Debug\net452\NLog.Etw.Tests.dll\" -appveyor -noshadow"  -returntargetcode -filter:"+[NLog.Etw]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"

artifacts:
  - path: 'artifacts\*.nupkg'
  - path: 'artifacts\*.snupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: 5tuxbM+Ujp0ZtaDCGYET23qKr6bJWo/Vzxlf7uTbspaf8R1R7sIe1JqSDHZoK1gV
  on:
    branch: master
